services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goshorter
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d goshorter']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  goshorter:
    build:
      context: .
      dockerfile: Dockerfile
    image: xyma8/go_shorter:1.0.0
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - '8080:8080'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: goshorter
      POSTGRES_SSLMODE: disable
      BACKEND_PROTOCOL: http
      BACKEND_HOST: localhost:8080
volumes:
  pgdata:
